"""init tables

Revision ID: 05082bfbcbdb
Revises: 
Create Date: 2026-02-11 09:47:33.968869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05082bfbcbdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_name', sa.String(length=255), nullable=False, comment='Form: Complaint name *'),
    sa.Column('quality_issue_warranty', sa.String(length=100), nullable=True, comment='Form: Quality issue / Warranty *'),
    sa.Column('customer', sa.String(length=255), nullable=True, comment='Form: Customer *'),
    sa.Column('customer_plant_name', sa.String(length=255), nullable=True, comment='Form: Customer plant name *'),
    sa.Column('avocarbon_plant', sa.Enum('MONTERREY', 'KUNSHAN', 'CHENNAI', 'DAUGU', 'TIANJIN', 'POITIERS', 'FRANKFURT', 'SCEET', 'SAME', 'AMIENS', 'ANHUI', 'KOREA', name='plant_enum'), nullable=True, comment='Form: AVOCarbon plant *'),
    sa.Column('avocarbon_product_type', sa.String(length=100), nullable=True, comment='Form: AVOCarbon product type *'),
    sa.Column('potential_avocarbon_process_linked_to_problem', sa.String(length=500), nullable=True, comment='Form: Potential AVOCarbon process *'),
    sa.Column('product_line', sa.Enum('ASSEMBLY', 'BRUSH', 'CHOKE', 'SEAL', 'FRICTION', name='product_line_enum'), nullable=False, comment='Form: Product line *'),
    sa.Column('concerned_application', sa.String(length=255), nullable=True, comment='Form: Concerned application *'),
    sa.Column('customer_complaint_date', sa.Date(), nullable=True, comment='Form: Customer complaint date *'),
    sa.Column('complaint_opening_date', sa.Date(), nullable=False, comment='Form: Complaint opening date *'),
    sa.Column('complaint_description', sa.Text(), nullable=True, comment='Form: Complaint description * (max 2000 chars)'),
    sa.Column('defects', sa.String(length=255), nullable=True, comment='Form: Defects *'),
    sa.Column('quality_manager', sa.Integer(), nullable=True, comment='Form: Quality manager *'),
    sa.Column('repetitive_complete_with_number', sa.Text(), nullable=True, comment='Form: REPETITIVE number *'),
    sa.Column('reported_by', sa.Integer(), nullable=False, comment='User who created complaint'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='User assigned to handle complaint'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='open|in_progress|under_review|resolved|closed|rejected'),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='low|medium|high|critical'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='low|normal|high|urgent'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quality_manager'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_assigned_to'), 'complaints', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_customer_complaint_date'), 'complaints', ['customer_complaint_date'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_product_line'), 'complaints', ['product_line'], unique=False)
    op.create_index(op.f('ix_complaints_quality_manager'), 'complaints', ['quality_manager'], unique=False)
    op.create_index(op.f('ix_complaints_reported_by'), 'complaints', ['reported_by'], unique=False)
    op.create_index(op.f('ix_complaints_severity'), 'complaints', ['severity'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False, comment='report|ikb|evidence'),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA-256 hash'),
    sa.CheckConstraint("purpose IN ('report', 'ikb', 'evidence')", name='check_purpose'),
    sa.CheckConstraint('size_bytes > 0', name='check_file_size'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index(op.f('ix_files_purpose'), 'files', ['purpose'], unique=False)
    op.create_index(op.f('ix_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_table('kb_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True, comment='Full-text search vector'),
    sa.Column('section_hint', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'chunk_index', name='unique_file_chunk')
    )
    op.create_index('idx_kb_chunks_tsv', 'kb_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_kb_chunks_file_id'), 'kb_chunks', ['file_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('plant', sa.Enum('MONTERREY', 'KUNSHAN', 'CHENNAI', 'DAUGU', 'TIANJIN', 'POITIERS', 'FRANKFURT', 'SCEET', 'SAME', 'AMIENS', 'ANHUI', 'KOREA', name='plant_enum'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft|in_progress|submitted|under_review|approved|rejected'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_complaint_id'), 'reports', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_reports_created_by'), 'reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_reports_plant'), 'reports', ['plant'], unique=False)
    op.create_index(op.f('ix_reports_report_number'), 'reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_reports_reviewed_by'), 'reports', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('report_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('step_code', sa.String(length=10), nullable=False, comment='D1|D2|D3|D4|D5|D6|D7|D8'),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft|submitted|validated|rejected'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible JSON storage for step-specific data'),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'step_code', name='unique_report_step')
    )
    op.create_index('idx_report_steps_data', 'report_steps', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_report_steps_created_at'), 'report_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_steps_report_id'), 'report_steps', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_steps_status'), 'report_steps', ['status'], unique=False)
    op.create_table('step_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_step_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('attachment_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_step_id'], ['report_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_step_id', 'file_id', name='unique_step_file')
    )
    op.create_index(op.f('ix_step_files_file_id'), 'step_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_step_files_report_step_id'), 'step_files', ['report_step_id'], unique=False)
    op.create_table('step_validation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_step_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False, comment='pass|fail'),
    sa.Column('missing', sa.ARRAY(sa.Text()), nullable=True, comment='Missing elements'),
    sa.Column('issues', sa.ARRAY(sa.Text()), nullable=True, comment='Identified issues'),
    sa.Column('suggestions', sa.ARRAY(sa.Text()), nullable=True, comment='Improvement suggestions'),
    sa.Column('professional_rewrite', sa.Text(), nullable=True, comment='AI-generated rewrite'),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_step_id'], ['report_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_validation_decision'), 'step_validation', ['decision'], unique=False)
    op.create_index(op.f('ix_step_validation_report_step_id'), 'step_validation', ['report_step_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_validation_report_step_id'), table_name='step_validation')
    op.drop_index(op.f('ix_step_validation_decision'), table_name='step_validation')
    op.drop_table('step_validation')
    op.drop_index(op.f('ix_step_files_report_step_id'), table_name='step_files')
    op.drop_index(op.f('ix_step_files_file_id'), table_name='step_files')
    op.drop_table('step_files')
    op.drop_index(op.f('ix_report_steps_status'), table_name='report_steps')
    op.drop_index(op.f('ix_report_steps_report_id'), table_name='report_steps')
    op.drop_index(op.f('ix_report_steps_created_at'), table_name='report_steps')
    op.drop_index('idx_report_steps_data', table_name='report_steps', postgresql_using='gin')
    op.drop_table('report_steps')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reviewed_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_number'), table_name='reports')
    op.drop_index(op.f('ix_reports_plant'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_complaint_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_kb_chunks_file_id'), table_name='kb_chunks')
    op.drop_index('idx_kb_chunks_tsv', table_name='kb_chunks', postgresql_using='gin')
    op.drop_table('kb_chunks')
    op.drop_index(op.f('ix_files_uploaded_by'), table_name='files')
    op.drop_index(op.f('ix_files_purpose'), table_name='files')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_severity'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reported_by'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_quality_manager'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_product_line'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_complaint_date'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_to'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
