"""add due_date and closed_at to complaints

Revision ID: 3831822e043f
Revises: f31437e9a711
Create Date: 2026-02-17 14:48:37.083321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3831822e043f'
down_revision: Union[str, Sequence[str], None] = 'f31437e9a711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('due_date', sa.DateTime(), nullable=True, comment='Expected resolution date'))
    op.add_column('complaints', sa.Column('closed_at', sa.DateTime(), nullable=True, comment='When complaint was closed'))
    op.drop_constraint(op.f('complaints_reference_number_key'), 'complaints', type_='unique')
    op.create_index(op.f('ix_complaints_closed_at'), 'complaints', ['closed_at'], unique=False)
    op.create_index(op.f('ix_complaints_due_date'), 'complaints', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_due_date'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_closed_at'), table_name='complaints')
    op.create_unique_constraint(op.f('complaints_reference_number_key'), 'complaints', ['reference_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('complaints', 'closed_at')
    op.drop_column('complaints', 'due_date')
    # ### end Alembic commands ###
